feat: add possibility to upgrade bootloader on upgrade
This is done in old init when the old kernel is still loaded from old
bootloader.
Old init will replace kernel, init and install bootloader.

On next reboot, new bootloader will load new kernel and new init

diff --git a/package/recalbox-initramfs/init b/package/recalbox-initramfs/init
--- a/package/recalbox-initramfs/init
+++ b/package/recalbox-initramfs/init
@@ -4,6 +4,7 @@
 #!/bin/ash
 
 safeboot="/overlay_root/.safeboot"
+bootloaderlog="/boot_root/boot/bl-update.log"
 
 do_splash() {
     img="$1"
@@ -76,6 +77,61 @@ do_update() {
     # delete content of /boot_root/update/
     rm -rf /boot_root/update/
     mkdir /boot_root/update/
+
+    # remove useless files
+    rm /boot_root/boot.lst
+    rm /boot_root/pre-upgrade.sh
+    return 0 # mask errors
+}
+
+get_boot_device() {
+    # return /dev entry which is mounted under /boot_root
+    mount >&2
+    part=$(mount | sed '/\/boot_root/!d;s/\son\s*.*//')
+    part=${part#/dev/}
+    disk=$(readlink /sys/class/block/$part)
+    disk=$(dirname $disk)
+    disk=/dev/$(basename $disk)
+    echo $disk
+}
+
+do_flash() {
+    # flash bootloader:
+    # $1 file name to flash
+    # $2 device where to flash
+    # $3 sector where to flash
+    echo "will flash $1 on $2 at sector $3"
+    dd if="$1" of="$2" conv=notrunc seek="$3" 2>&1
+}
+
+do_bootloader_update() {
+    echo "==========================="
+    boot_device=$(get_boot_device)
+    if [ -z "$boot_device" ]; then
+        echo "boot device not found..." >&2
+        return 1
+    fi
+
+    echo "boot_device=$boot_device"
+    error=0
+    find /boot_root/boot/bootloader -type f | while read -r file; do
+        echo "found $file"
+        sector_dir=$(dirname $file)
+        sector=$(basename $sector_dir)
+        max_tries=3
+        while [ $max_tries -gt 0 ]; do
+            max_tries=$((max_tries-1))
+            if do_flash "$file" "$boot_device" "$sector"; then
+                echo "flash of $file done"
+                max_tries=0
+            else
+                echo "flash of $file ended in error, $max_tries tries left"
+                error=1
+            fi
+        done
+        rm -rf "$sector_dir"
+    done
+    return $error
 }
 
 do_root() {
@@ -116,6 +172,7 @@ do_root() {
     if check_update ; then
         if ! do_update ; then return 1; fi
         updated="1"
+        [ -d /boot_root/boot/bootloader ] && do_bootloader_update >>$bootloaderlog 2>&1
     fi
 
     # Get overlay mount
