feat(ci): update NOOBS asset generation to new partitions scheme
This commit adapts how we tell NOOBS to create partitions and
filesystems to our recent change of partitioning scheme (which also
introduces SquashFS and ExFAT for SHARE partition).

Unfortunately, NOOBS is unable to create ExFAT filesystems. NOOBS only
creates a maximised partition but does not create any filesystem into
it.
ExFAT filesystem creation is done on first boot in `S11share`.

Here is a quick history if failed attempts that led to this solution.

1st attempt was to create only BOOT partition from NOOBS and to create
all other partitions and filesystems from `S11share` to keep this logic
in one single place. It failed because `parted` refuses to resize an
extended partition which contains the logical partition mounted as `/`.

2nd attempt was to workaround previous failure by copying content of
`/` in a tmpfs and use `pivot_root` in order to unmount original on-disk
BOOT partition and resize it. It failed because Pi Zero does not have
enough RAM to do this.

3rd attempt was to use `fdisk` rather than `parted` to overwrite the
partition table in place. It failed because `fdisk` is made for human
and has highly inconsistent input (it "guesses" a lot of things for
the user), also I witnessed some very strange behaviour in its
auto-alignment suggestions.

4th attempt was to forget about keeping all partitions logic in a single
place, and let NOOBS do all the partitioning and filesystem
creation/population on its side. It failed because NOOBS does not
support creating ExFAT filesystems.

5th attempt is this commit: we create all partitions and all filesystems
(except for SHARE, which is ExFAT) from NOOBS, then detect missing SHARE
filesystem on first boot from `S11share` and create it.

diff --git a/board/recalbox/fsoverlay/etc/init.d/S11share b/board/recalbox/fsoverlay/etc/init.d/S11share
--- a/board/recalbox/fsoverlay/etc/init.d/S11share
+++ b/board/recalbox/fsoverlay/etc/init.d/S11share
@@ -242,6 +242,17 @@ mountInternal() {
   fi
 }
 
+# partitionHasAFilesystem <partition>
+#   → returns success (0) if a filesystem is detected in the given partition (block device)
+#     returns failure (1) otherwise
+#   NOTE: Busybox implementation of `blkid` is very scarce: it supports no option at all
+#         and symply displays all tags when a filesystem is detected, nothing otherwise
+partitionHasAFilesystem() {
+  local partition="${1}"
+
+  [ -n "$(blkid "${partition}")" ]
+}
+
 ########
 # MAIN #
 ########
@@ -250,6 +261,13 @@ mountInternal() {
 # (we do this regardless of `sharedevice` mode configured below)
 if [ ! -b "${sharePartition}" ]; then
   createMissingPartitions
+fi
+
+# Create ExFAT filesystem in SHARE partition if it does not exist
+# (this is the case on first boot after NOOBS partition, because
+# NOOBS does not support creating ExFAT filesystems)
+if ! partitionHasAFilesystem "${sharePartition}"; then
+  mkexfatfs -n SHARE "${sharePartition}"
 fi
 
 # Read `sharedevice` in /boot/recalbox-boot.conf, it can contain:
