squashfs: fix upgrade

diff --git a/board/recalbox/fsoverlay/etc/init.d/S11upgrade b/board/recalbox/fsoverlay/etc/init.d/S11upgrade
--- a/board/recalbox/fsoverlay/etc/init.d/S11upgrade
+++ b/board/recalbox/fsoverlay/etc/init.d/S11upgrade
@@ -140,7 +140,7 @@ do_upgrade_squashfs() {
         echo "title Upgrading the squashfs"
         while true
         do
-            sizeCopied=`stat "/$realRoot/recalbox.squashfs.upgrade" | grep "Size:" | tr -s ' ' | cut -d ' ' -f 3 || echo "0"`
+            sizeCopied=`stat "$realRoot/recalbox.squashfs.upgrade" | grep "Size:" | tr -s ' ' | cut -d ' ' -f 3 || echo "0"`
             let sizePercentage=${sizeCopied}00/${totalSize}
             echo "percent ${sizePercentage}"
             sleep 1
@@ -148,7 +148,7 @@ do_upgrade_squashfs() {
     ) | /recalbox/scripts/shell2fb.py &
     # Copy the file
     xz -dc --threads=0 < "${ROOTTAR}" > "$realRoot/recalbox.squashfs.upgrade" && \
-    mv $realRoot/recalbox.squashfs $realRoot/recalbox.squashfs.downgrade && \
+    ( [ -e $realRoot/recalbox.squashfs ] && mv $realRoot/recalbox.squashfs $realRoot/recalbox.squashfs.downgrade || true ) &&
     mv $realRoot/recalbox.squashfs.upgrade $realRoot/recalbox.squashfs \
     || return 1
     umount "$realRoot"
@@ -158,7 +158,7 @@ do_upgrade_squashfs() {
 mount_tmp_root() {
     realRoot=`/recalbox/scripts/recalbox-part.sh system`
     [ -z "$realRoot" ] && return 1
-    # There is a trick: mounting / as RW can fail. So try RO + remount RW AND RW
+    # There is a trick: mounting / as RW can fail. So try RO + remount RW AND  simply mount RW
     rootPath=/tmp/realroot
     mkdir -p "$rootPath" && \
     ( mount -r "$realRoot" "$rootPath" 2>/dev/null && mount -o remount, rw "$rootPath" || mount "$realRoot" "$rootPath" ) && \
