feat(upgrade): always check sha1sum before upgrading recalbox

diff --git a/board/recalbox/fsoverlay/etc/init.d/S11upgrade b/board/recalbox/fsoverlay/etc/init.d/S11upgrade
--- a/board/recalbox/fsoverlay/etc/init.d/S11upgrade
+++ b/board/recalbox/fsoverlay/etc/init.d/S11upgrade
@@ -19,6 +19,7 @@ clean_boot_update() {
 
 failed_clean_exit() {
   clean_boot_update
+  touch /tmp/upgradefailed
   fbv2 -k -i /recalbox/system/resources/offline-install-error.jpg
   sleep 10
   exit 1
@@ -34,16 +35,21 @@ SHAREUPDATEDIR=/recalbox/share/system/upgrade/
 if [[ -f $UPDATEFILE ]]; then
   recallog -f upgrade.log "upgrade found! moving ${UPDATEFILE} to SHARE as $(basename "${UPDATEFILE_UNCOMPRESSED}")"
   fbv2 -k -i /recalbox/system/resources/offline-install-0.jpg
-  if [ -f "$UPDATEFILE_SHA1" ]; then
-    recallog -f upgrade.log "checking SHA1"
-    if ! ( cd "$UPDATEDIR" && sha1sum -c "$UPDATEFILE_SHA1" ); then
-      recallog -f upgrade.log "SHA1 checking failed, removing stale files. Exiting..."
-      failed_clean_exit
-    fi
+
+  if [ ! -f "$UPDATEFILE_SHA1" ]; then
+    recallog -f upgrade.log "upgrade SHA1 not found, skipping upgrade"
+    failed_clean_exit
   fi
+
+  recallog -f upgrade.log "checking SHA1"
+  if ! ( cd "$UPDATEDIR" && sha1sum -c "$UPDATEFILE_SHA1" ); then
+    recallog -f upgrade.log "SHA1 checking failed, removing stale files. Exiting..."
+    failed_clean_exit
+  fi
+  
   clean_dir "$SHAREUPDATEDIR"
   if ! unxz -c "${UPDATEFILE}" >"$SHAREUPDATEDIR/$(basename "$UPDATEFILE_UNCOMPRESSED")"; then
-      recallog -f upgrade.log "decompression failed, removing stale files. Exiting..."
+    recallog -f upgrade.log "decompression failed, removing stale files. Exiting..."
     failed_clean_exit
   fi
   clean_dir "$UPDATEDIR"
